# Generated by Django 5.2.4 on 2025-09-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
    ]
